// <auto-generated />
using System;
using Hamsterdagis_Dessi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hamsterdagis_Dessi.Migrations
{
    [DbContext(typeof(HamsterAppContext))]
    [Migration("20210331133316_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BackEnd_database.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Logg_ActivitiesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Logg_ActivitiesId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arrival"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DayCage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Exercise"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PickUp"
                        });
                });

            modelBuilder.Entity("BackEnd_database.Cage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Cages");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        });
                });

            modelBuilder.Entity("BackEnd_database.Cage_Buddies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfBuddies")
                        .HasColumnType("int");

                    b.Property<int>("CageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CageId");

                    b.ToTable("Cage_Buddies");
                });

            modelBuilder.Entity("BackEnd_database.ExerciseArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountInArea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExerciseAreas");
                });

            modelBuilder.Entity("BackEnd_database.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gender_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender_Type = "Female"
                        },
                        new
                        {
                            Id = 2,
                            Gender_Type = "Male"
                        });
                });

            modelBuilder.Entity("BackEnd_database.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Cage_BuddiesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExerciseAreaId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Hamster_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Logg_ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeForLastExercise")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("Cage_BuddiesId");

                    b.HasIndex("ExerciseAreaId");

                    b.HasIndex("GenderId");

                    b.HasIndex("Logg_ActivitiesId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4,
                            GenderId = 2,
                            Hamster_Name = "Rufus",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 12,
                            GenderId = 1,
                            Hamster_Name = "Lisa",
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 11,
                            GenderId = 2,
                            Hamster_Name = "Fluff",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 10,
                            GenderId = 2,
                            Hamster_Name = "Nibbler",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 9,
                            GenderId = 2,
                            Hamster_Name = "Sneaky",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 6,
                            Age = 8,
                            GenderId = 1,
                            Hamster_Name = "Sussi",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 7,
                            Age = 7,
                            GenderId = 1,
                            Hamster_Name = "Mulan",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 8,
                            Age = 6,
                            GenderId = 1,
                            Hamster_Name = "Miss Diggy",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 9,
                            Age = 5,
                            GenderId = 2,
                            Hamster_Name = "Kalle",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 10,
                            Age = 4,
                            GenderId = 2,
                            Hamster_Name = "Kurt",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 11,
                            Age = 4,
                            GenderId = 1,
                            Hamster_Name = "Starlight",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 12,
                            Age = 3,
                            GenderId = 2,
                            Hamster_Name = "Chivas",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 13,
                            Age = 3,
                            GenderId = 1,
                            Hamster_Name = "Malin",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 14,
                            Age = 24,
                            GenderId = 2,
                            Hamster_Name = "Bulle",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 15,
                            Age = 23,
                            GenderId = 2,
                            Hamster_Name = "Beppe",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 16,
                            Age = 22,
                            GenderId = 1,
                            Hamster_Name = "Bobo",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 17,
                            Age = 21,
                            GenderId = 1,
                            Hamster_Name = "Robin",
                            OwnerId = 13
                        },
                        new
                        {
                            Id = 18,
                            Age = 20,
                            GenderId = 1,
                            Hamster_Name = "Amber",
                            OwnerId = 14
                        },
                        new
                        {
                            Id = 19,
                            Age = 19,
                            GenderId = 1,
                            Hamster_Name = "Kimber",
                            OwnerId = 15
                        },
                        new
                        {
                            Id = 20,
                            Age = 18,
                            GenderId = 1,
                            Hamster_Name = "Ruby",
                            OwnerId = 16
                        },
                        new
                        {
                            Id = 21,
                            Age = 16,
                            GenderId = 1,
                            Hamster_Name = "Fiffi",
                            OwnerId = 17
                        },
                        new
                        {
                            Id = 22,
                            Age = 16,
                            GenderId = 1,
                            Hamster_Name = "Neko",
                            OwnerId = 18
                        },
                        new
                        {
                            Id = 23,
                            Age = 15,
                            GenderId = 2,
                            Hamster_Name = "Clint",
                            OwnerId = 19
                        },
                        new
                        {
                            Id = 24,
                            Age = 14,
                            GenderId = 2,
                            Hamster_Name = "Sauron",
                            OwnerId = 20
                        },
                        new
                        {
                            Id = 25,
                            Age = 12,
                            GenderId = 1,
                            Hamster_Name = "Gittan",
                            OwnerId = 21
                        },
                        new
                        {
                            Id = 26,
                            Age = 110,
                            GenderId = 2,
                            Hamster_Name = "Crawler",
                            OwnerId = 22
                        },
                        new
                        {
                            Id = 27,
                            Age = 9,
                            GenderId = 1,
                            Hamster_Name = "Mimmi",
                            OwnerId = 23
                        },
                        new
                        {
                            Id = 28,
                            Age = 8,
                            GenderId = 2,
                            Hamster_Name = "Marvel",
                            OwnerId = 24
                        },
                        new
                        {
                            Id = 29,
                            Age = 7,
                            GenderId = 2,
                            Hamster_Name = "Storm",
                            OwnerId = 25
                        },
                        new
                        {
                            Id = 30,
                            Age = 6,
                            GenderId = 1,
                            Hamster_Name = "Busan",
                            OwnerId = 26
                        });
                });

            modelBuilder.Entity("BackEnd_database.Logg_Activities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Logg_Activities");
                });

            modelBuilder.Entity("BackEnd_database.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kallegurra Aktersnurra"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carl Hamilton"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lisa Nilsson"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jan Hallgren"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ottilla Murkwood"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Anfers Murkwood"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anna Book"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pernilla Wahlgren"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bianca Ingrosso"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lorenzo Lamas"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bobby Ewing"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Hedy Lamar"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bette Davis"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kim Carnes"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mork of Ork"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Mindy Mendel"
                        },
                        new
                        {
                            Id = 17,
                            Name = "GW Hansson"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Pia Hansson"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bo Ek"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Anna Al"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Hans Björk"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Carita Gran"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Mia Eriksson"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Anna Linström"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Lennart Berg"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bo Bergman"
                        });
                });

            modelBuilder.Entity("BackEnd_database.Activity", b =>
                {
                    b.HasOne("BackEnd_database.Logg_Activities", null)
                        .WithMany("Activities")
                        .HasForeignKey("Logg_ActivitiesId");
                });

            modelBuilder.Entity("BackEnd_database.Cage_Buddies", b =>
                {
                    b.HasOne("BackEnd_database.Cage", "Cage")
                        .WithMany()
                        .HasForeignKey("CageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("BackEnd_database.Hamster", b =>
                {
                    b.HasOne("BackEnd_database.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("BackEnd_database.Cage_Buddies", null)
                        .WithMany("Hamsters")
                        .HasForeignKey("Cage_BuddiesId");

                    b.HasOne("BackEnd_database.ExerciseArea", null)
                        .WithMany("Hamsters")
                        .HasForeignKey("ExerciseAreaId");

                    b.HasOne("BackEnd_database.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd_database.Logg_Activities", null)
                        .WithMany("Hamsters")
                        .HasForeignKey("Logg_ActivitiesId");

                    b.HasOne("BackEnd_database.Owner", "Owner")
                        .WithMany("Hamsters")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Gender");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BackEnd_database.Cage_Buddies", b =>
                {
                    b.Navigation("Hamsters");
                });

            modelBuilder.Entity("BackEnd_database.ExerciseArea", b =>
                {
                    b.Navigation("Hamsters");
                });

            modelBuilder.Entity("BackEnd_database.Logg_Activities", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Hamsters");
                });

            modelBuilder.Entity("BackEnd_database.Owner", b =>
                {
                    b.Navigation("Hamsters");
                });
#pragma warning restore 612, 618
        }
    }
}
